# Site settings
title: Pando CSS
email: design.wuif@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Bootstrap design wrapper with additional styles and functions
baseurl: "/pando"
url: "https://wuifdesign.github.io/pando"
github_username:  wuifdesign
encoding: utf-8

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
